version: '3'
services:
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/es_data/:/usr/share/elasticsearch/data/

  kibana:
    image: kibana:6.8.2
    container_name: kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  fess:
    image: codelibs/fess:13.2.0
    container_name: fess
    ports:
      - "10084:8080"
    volumes:
      - ./fess/docs/:/docs/

